blueprint: page

title: Page

columns:
  - width: 1/1
    fields:
      htmlContent:
        width: 3/4
        type: blocks
        label: Contenu
        fieldsets:
          - text
          - image
