title: Default

tabs:
  content:
    fields:
      sections:
        type: layout
        layouts:
          - "1/1"
          - "1/2, 1/2"
        selector:
          size: huge
          columns: 2
        fieldsets:
          - text
          - image
          - file
          - link
          - hr
          - newsletter
          - group
  children:
    label: Sous-pages
    sections:
      pages: 
        template: default