blueprint: page

title: Page

columns:
  - width: 1/1
    fields:
      layout:
        label: Contenu
        type: layout
        layouts:
          - "1/1"
          - "1/2"
        selector:
          columns: 2
        fieldsets:
          - text
          - image
        settings:
          fields:
            color:
              label: Couleur
              type: color
              mode: options
              options:
                - "1e1f19"
                - "ed8ed9"
                - "ea5932"
                - "273aaa"
                - "66aff3"
                - "f5ca4f"
                - "fffd58"
                - "ed9275"
                - "3b7834"
                - "32576a"
                - "ec7440"
                - "252e30"
                - "ae8d5a"
                - "2a3260"
                - "a1f7e1"
                - "665ace"
                - "bffa92"
                - "683e3e"
                - "312951"
                - "7e7972"
                - "fefc85"
