blueprint: page

title: Page

columns:
  - width: 2/3
    sections:
      intro:
        type: fields
        fields:
          intro_layout: fields/layout
      experiences:
        type: fields
        fields:
          experiences_headline:
            type: headline
            label: Expériences
          experiences_layout: fields/layout
      experiences_pages:
        type: pages
        label: Expériences
        templates: experiences
      objects:
        type: fields
        fields:
          objects_headline:
            type: headline
            label: Objets
          objects_layout: fields/layout
      objects_pages:
        type: pages
        label: Objets
        templates: objects
      outro:
        type: fields
        fields:
          outro_layout:
            label: Contenu
            type: layout
            layouts:
              - "1/1"
            selector:
              columns: 1
            fieldsets:
              - text
              - image
            settings:
              fields:
                color:
                  label: Couleur
                  extends: fields/color
  - width: 1/3
    fields:
      header:
        label: Bloc en-tête
        extends: fields/text
      header_color:
        label: Couleur de l'en-tête
        extends: fields/color