blueprint: page

name: Texte
icon: text
wysiwyg: true
preview: text
fields:
  text:
    type: writer
    headings:
      - 2
      - 3
      - 4
    placeholder: field.blocks.text.placeholder
    marks:
      - underline
      - link
      - email
    nodes:
      - heading
      - bulletList
      - orderedList
